name: CI
on:
  pull_request:
    branches:
      - "main"

jobs:
  flutter-test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@1
        with:
          java-version: "1.x"
      - name: Setup flutter
        uses: subosito/flutter-actions@v2
        with:
          channel: "stable"
          cache: "true"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test