name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  flutter-test:
    name: Rub flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-actions@v1
        with:
          channel: "stable"
      - rub: flutter pub get
      - run: flutter analyze
      - run: flutter test